name: upnp_explorer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.2.1
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  http: ^0.13.4
  intl: ^0.17.0
  open_settings: ^2.0.2
  package_info: ^2.0.2
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.8
  sprintf: ^6.0.0
  udp: ^3.0.3
  url_launcher: ^6.0.12
  xml: ^5.3.0
  xml2json: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  mockito: ^5.0.16
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
